[versions]
spring-boot = "4.0.7"
spring-batch = "6.0.4"
# spring-jdbc version should follow minor version described in 'spring-framework.version'
# https://github.com/spring-projects/spring-batch/blob/main/pom.xml
spring-jdbc = "7.0.6"
slf4j = "2.0.17"
reactor-core = "3.8.4"
findbugs-jsr305 = "3.0.2"
jspecify = "1.0.0"

# test-only
junit = "6.0.+"
assertj = "3.27.+"
mockito = "5.20.+"
mockk = "1.14.+"
h2 = "2.4.+"
log4j = "2.25.+"

[libraries]
spring-boot-autoconfigure = { module = "org.springframework.boot:spring-boot-autoconfigure", version.ref = "spring-boot" }
spring-batch-core = { module = "org.springframework.batch:spring-batch-core", version.ref = "spring-batch" }
spring-jdbc = { module = "org.springframework:spring-jdbc", version.ref = "spring-jdbc" }
slf4j = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
reactor-core = { module = "io.projectreactor:reactor-core", version.ref = "reactor-core" }
findbugs-jsr305 = { module = "com.google.code.findbugs:jsr305", version.ref = "findbugs-jsr305" }
jspecify = { module = "org.jspecify:jspecify", version.ref = "jspecify" }

# test-only
junit = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit" }
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
mockito = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
spring-boot-test = { module = "org.springframework.boot:spring-boot-test", version.ref = "spring-boot" }
spring-batch-test = { module = "org.springframework.batch:spring-batch-test", version.ref = "spring-batch" }
h2 = { module = "com.h2database:h2", version.ref = "h2" }
log4j = { module = "org.apache.logging.log4j:log4j-slf4j-impl", version.ref = "log4j" }

[bundles]
test-java = ["junit", "assertj", "mockito"]
test-kotlin = ["junit", "assertj", "mockk"]
