spring:
  profiles:
    active: local
  h2:
    console:
      enabled: true
      path: /h2-console # enable h2 console
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: embedded
      platform: h2
