name: Deploy

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  workflow_dispatch:
    inputs:
      commit_id:
        description: 'Git commit id'
        required: true

jobs:
  build:
    steps:
      - name: Setup Commit ID
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "COMMIT_ID=${{ github.event.inputs.commit_id }}" >> ${GITHUB_ENV}
          else
            echo "COMMIT_ID=${{ github.sha }}" >> ${GITHUB_ENV}
          fi

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ env.COMMIT_ID }}
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run check
        run: ./gradlew clean build

      - name: Publish
        run: ./gradlew publish --no-parallel
        env:
          MAVEN_USER: ${{ secrets.MAVEN_USER } }
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD } }
          ORG_GRADLE_PROJECT_signingKeyId: ${{ secrets.ORG_GRADLE_PROJECT_signingKeyId } }
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.ORG_GRADLE_PROJECT_signingKey } }
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.ORG_GRADLE_PROJECT_signingPassword } }
